# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import marketplace_pb2 as marketplace__pb2


class MarketplaceServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSeller = channel.unary_unary(
                '/marketplace.MarketplaceService/RegisterSeller',
                request_serializer=marketplace__pb2.SellerRegistration.SerializeToString,
                response_deserializer=marketplace__pb2.Response.FromString,
                )
        self.SellItem = channel.unary_unary(
                '/marketplace.MarketplaceService/SellItem',
                request_serializer=marketplace__pb2.ItemManagement.SerializeToString,
                response_deserializer=marketplace__pb2.Response.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/marketplace.MarketplaceService/UpdateItem',
                request_serializer=marketplace__pb2.ItemManagement.SerializeToString,
                response_deserializer=marketplace__pb2.Response.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/marketplace.MarketplaceService/DeleteItem',
                request_serializer=marketplace__pb2.ItemManagement.SerializeToString,
                response_deserializer=marketplace__pb2.Response.FromString,
                )
        self.DisplaySellerItems = channel.unary_stream(
                '/marketplace.MarketplaceService/DisplaySellerItems',
                request_serializer=marketplace__pb2.SellerRegistration.SerializeToString,
                response_deserializer=marketplace__pb2.Item.FromString,
                )
        self.SearchItem = channel.unary_stream(
                '/marketplace.MarketplaceService/SearchItem',
                request_serializer=marketplace__pb2.BuyerOperation.SerializeToString,
                response_deserializer=marketplace__pb2.Item.FromString,
                )
        self.BuyItem = channel.unary_unary(
                '/marketplace.MarketplaceService/BuyItem',
                request_serializer=marketplace__pb2.BuyerOperation.SerializeToString,
                response_deserializer=marketplace__pb2.Response.FromString,
                )
        self.AddToWishList = channel.unary_unary(
                '/marketplace.MarketplaceService/AddToWishList',
                request_serializer=marketplace__pb2.BuyerOperation.SerializeToString,
                response_deserializer=marketplace__pb2.Response.FromString,
                )
        self.RateItem = channel.unary_unary(
                '/marketplace.MarketplaceService/RateItem',
                request_serializer=marketplace__pb2.BuyerOperation.SerializeToString,
                response_deserializer=marketplace__pb2.Response.FromString,
                )
        self.NotifyClient = channel.unary_stream(
                '/marketplace.MarketplaceService/NotifyClient',
                request_serializer=marketplace__pb2.Address.SerializeToString,
                response_deserializer=marketplace__pb2.Notification.FromString,
                )


class MarketplaceServiceServicer(object):
    """Service definition
    """

    def RegisterSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWishList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketplaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=marketplace__pb2.SellerRegistration.FromString,
                    response_serializer=marketplace__pb2.Response.SerializeToString,
            ),
            'SellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SellItem,
                    request_deserializer=marketplace__pb2.ItemManagement.FromString,
                    response_serializer=marketplace__pb2.Response.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=marketplace__pb2.ItemManagement.FromString,
                    response_serializer=marketplace__pb2.Response.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=marketplace__pb2.ItemManagement.FromString,
                    response_serializer=marketplace__pb2.Response.SerializeToString,
            ),
            'DisplaySellerItems': grpc.unary_stream_rpc_method_handler(
                    servicer.DisplaySellerItems,
                    request_deserializer=marketplace__pb2.SellerRegistration.FromString,
                    response_serializer=marketplace__pb2.Item.SerializeToString,
            ),
            'SearchItem': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchItem,
                    request_deserializer=marketplace__pb2.BuyerOperation.FromString,
                    response_serializer=marketplace__pb2.Item.SerializeToString,
            ),
            'BuyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyItem,
                    request_deserializer=marketplace__pb2.BuyerOperation.FromString,
                    response_serializer=marketplace__pb2.Response.SerializeToString,
            ),
            'AddToWishList': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishList,
                    request_deserializer=marketplace__pb2.BuyerOperation.FromString,
                    response_serializer=marketplace__pb2.Response.SerializeToString,
            ),
            'RateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RateItem,
                    request_deserializer=marketplace__pb2.BuyerOperation.FromString,
                    response_serializer=marketplace__pb2.Response.SerializeToString,
            ),
            'NotifyClient': grpc.unary_stream_rpc_method_handler(
                    servicer.NotifyClient,
                    request_deserializer=marketplace__pb2.Address.FromString,
                    response_serializer=marketplace__pb2.Notification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.MarketplaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketplaceService(object):
    """Service definition
    """

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.MarketplaceService/RegisterSeller',
            marketplace__pb2.SellerRegistration.SerializeToString,
            marketplace__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.MarketplaceService/SellItem',
            marketplace__pb2.ItemManagement.SerializeToString,
            marketplace__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.MarketplaceService/UpdateItem',
            marketplace__pb2.ItemManagement.SerializeToString,
            marketplace__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.MarketplaceService/DeleteItem',
            marketplace__pb2.ItemManagement.SerializeToString,
            marketplace__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/marketplace.MarketplaceService/DisplaySellerItems',
            marketplace__pb2.SellerRegistration.SerializeToString,
            marketplace__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/marketplace.MarketplaceService/SearchItem',
            marketplace__pb2.BuyerOperation.SerializeToString,
            marketplace__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.MarketplaceService/BuyItem',
            marketplace__pb2.BuyerOperation.SerializeToString,
            marketplace__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToWishList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.MarketplaceService/AddToWishList',
            marketplace__pb2.BuyerOperation.SerializeToString,
            marketplace__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.MarketplaceService/RateItem',
            marketplace__pb2.BuyerOperation.SerializeToString,
            marketplace__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/marketplace.MarketplaceService/NotifyClient',
            marketplace__pb2.Address.SerializeToString,
            marketplace__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
